name: Build APK

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          workdir: .
          buildozer_cmd: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: picksound-android
          path: bin/*.apk
